services:
  - type: web
    name: ats-umn-presence
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 8000
